### ISSUE TITLE
Just clean up unreachable non-public stuff

### ISSUE THREAD

**Issue by i00** [BrokenEvent/ILStrip#1]
I ran this and it seemed to clean up stuff that was marked as public - I think that ILStrip should have an option to clean up stuff that is not publicly reachable... (rather than just specifying entry points)

**Comment by preseverence** [comment]
It has filters. Most of stuff should be internal by design, but you can make exclusions for public API (or things that you thing should be public API).

```CSharp
// exclude the target public API
stripper.MakeInternalExclusions.Add("MyNamespace.MyClass");
