### ISSUE TITLE
Feature proposal: option to specify referencing assemby

### ISSUE THREAD

**Issue by mikernet** [BrokenEvent/ILStrip#3]
This would allow this to run *before* ILMerge on a target library. Right now, as I understand it, you have to merge everything first, specify entry points and then run ILStrip and the whole combined assembly is stripped as a whole. I propose that adding this option will allow you to reverse that process and make this significantly easier to use in a lot of situations.

For example, imagine I'm developing MyLibrary, which references OtherLibrary. I don't want ILStrip to touch any types inside MyLibrary, just strip out unused types from OtherLibrary before merging. To do this, I could do `stripper.ReferencingAssembly = "MyLibrary"` or something similar.

Now I don't have to worry about managing exclusions to stuff in MyLibrary and everything in MyLibrary is added automatically as an entry point. The only thing I need to worry about is if I use reflection to access OtherLibrary types, but everything in MyLibrary is safe. I imagine in most cases people merging a library assembly don't want their own assembly to be stripped. I can then ILMerge the two assemblies afterwards and all is well.

This has the important (to me) benefit of working easily from the command line with a single option.

**Comment by preseverence** [comment]
You can use whatever pipeline you want. If you want to clean up `OtherLibrary` from things you don't want before merging and keep your own `MyLibrary` as it was - you can just run ILStrip on `OtherLibrary` before merging. Just specify the entry points for code you want to keep.

But, as I understand you, you want to scan `MyLibary` for code using from `OtherLibrary` and use that as entry points to clean up `OtherLibrary`.

**Comment by mikernet** [comment]
Right, exactly. Having to manually maintain an entry point list into OtherLibrary would be painful to say the least.

**Comment by preseverence** [comment]
This is not the direct intention of ILStrip but it will be a nice feature.

**Comment by mikernet** [comment]
If you'll accept a PR for this I might have some time to whip something up for this eventually.

**Comment by preseverence** [comment]
I will if it will be worth it. But this is interesting, so I'll go in this when I will have time.

**Comment by mikernet** [comment]
We have a fairly large common utility library that is used by many other libraries but we don't want to publish those other libraries with a dependency on a particular version of the utility library. Some might use 50 or 100 types from the utility library, while others might use 1 or 2. Being able to just use the utility library and have everything work without manually maintaining a list of 100 entry points whenever a type new type is used or an type is no longer used is key.

I'm more than willing to PR this feature, it'll be way less work than the alternative. We don't want to add 500kb to all those other libraries when they might only use a couple types from the utility library and I can't think of another way to accomplish that, unless you have another idea.

**Comment by preseverence** [comment]
Yes, I understand your case.

We can just add a counter to `AddUsedType`. It ignores all types used from another modules (not main of currently scanning assembly). We can just count uses from another assemblies instead. Something like Dictionary<string, List<string>> (assembly name, list of types used from it). And give it public access so you can get list of entry points from it.

**Comment by mikernet** [comment]
Or a method called "AddEntryPointsFromAssembly()" which scans another assembly and adds any entry points into the current assembly from it.

**Comment by preseverence** [comment]
Only as a helper one, which internally creates an another instance of ILStrip, performs scan and adds entry points from dictionary I described before. I want to avoid altering logic.

**Comment by mikernet** [comment]
Oh, I see what you're saying. Yeah that could work. I think with a tiny bit of refactoring you can do this with reusing existing logic in a more efficient manner than tracking every single type used in every single other assembly though.

**Comment by mikernet** [comment]
That info won't be used by the ILStrip instance being used to actually strip an assembly so it would be kind of a waste to do that on all instances everytime it scans.

**Comment by preseverence** [comment]
Yes, it will. But i don't think this will be something critical. Anyway, ILStrip's logic is separated to different methods, so you can use it just as a scanner without actual stripping. However, we can add a switch (I mean `boolean` property) which enables this counter. And it will be disabled by default. So if you need that data - just enable collection before scanning. And your helper method will do the same.
ILStrip has a powerfull IL scanner integrated with type collection. So we *have to* reuse it. Any other options, including another classes with another versions of scanner (or separating it into chain of inherited classes) will be too huge changes for such a little feature. Especially if we can avoid it.

**Comment by mikernet** [comment]
Makes sense!

**Comment by preseverence** [comment]
Look at this one.

**Comment by mikernet** [comment]
That's great, looks perfect! I'll try it out asap.

**Comment by preseverence** [comment]
Outdated.
